// Generated by https://quicktype.io

export interface SignUpPayload {
  name: string;
  email: string;
  password: string;
}

export interface SignUpResponse {
  data: SignUpProps;
}

export interface SignUpProps {
  id: string;
  name: string;
  email: string;
  password: string;
  updated_at: string;
  created_at: string;
}
