// Generated by https://quicktype.io
import CategoryProps from "./index";
export interface CreateCategoryResponse {
  data: CategoryProps;
}

export interface CreateCategoryPayload {
  name: string;
}
