import CategoryProps from "./index";
export type { DeleteCategoryPayload as GetCategoryPayload } from "./DeleteCategory";
// Generated by https://quicktype.io

export interface GetCategoryResponse {
  data: CategoryProps;
}
