// Generated by https://quicktype.io
import CategoryProps from "./index";
export interface GetListCategoryResponse {
  data: CategoryProps[];
  current_page: number;
  total_item: number;
  total_page: number;
}
